-- MySQL Script generated by MySQL Workbench
-- Thu Jan  2 20:00:10 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cotizador
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cotizador
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cotizador` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `cotizador` ;

-- -----------------------------------------------------
-- Table `cotizador`.`proyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cotizador`.`proyecto` ;

CREATE TABLE IF NOT EXISTS `cotizador`.`proyecto` (
  `id_proyecto` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_proyecto` VARCHAR(500) NULL DEFAULT NULL,
  `prefijo_interesado` VARCHAR(20) NULL DEFAULT NULL,
  `nombre_interesado` VARCHAR(200) NULL DEFAULT NULL,
  `apellido_interesado` VARCHAR(200) NULL DEFAULT NULL,
  `empresa_interesado` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id_proyecto`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cotizador`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cotizador`.`producto` ;

CREATE TABLE IF NOT EXISTS `cotizador`.`producto` (
  `id_producto` INT(11) NOT NULL AUTO_INCREMENT,
  `id_proyecto` INT(11) NULL DEFAULT NULL,
  `producto` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `id_proyecto` (`id_proyecto` ASC),
  CONSTRAINT `producto_ibfk_1`
    FOREIGN KEY (`id_proyecto`)
    REFERENCES `cotizador`.`proyecto` (`id_proyecto`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cotizador`.`caracteristica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cotizador`.`caracteristica` ;

CREATE TABLE IF NOT EXISTS `cotizador`.`caracteristica` (
  `id_caracteristica` INT(11) NOT NULL AUTO_INCREMENT,
  `caracteristica` VARCHAR(500) NULL DEFAULT NULL,
  `id_producto` INT(11) NULL DEFAULT NULL,
  `id_proyecto` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_caracteristica`),
  INDEX `id_producto` (`id_producto` ASC),
  INDEX `id_proyecto` (`id_proyecto` ASC),
  CONSTRAINT `caracteristica_ibfk_1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `cotizador`.`producto` (`id_producto`),
  CONSTRAINT `caracteristica_ibfk_2`
    FOREIGN KEY (`id_proyecto`)
    REFERENCES `cotizador`.`proyecto` (`id_proyecto`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cotizador`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cotizador`.`categoria` ;

CREATE TABLE IF NOT EXISTS `cotizador`.`categoria` (
  `id_categoria` INT(11) NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cotizador`.`clase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cotizador`.`clase` ;

CREATE TABLE IF NOT EXISTS `cotizador`.`clase` (
  `id_clase` INT(11) NOT NULL AUTO_INCREMENT,
  `clase` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`id_clase`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cotizador`.`tamanio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cotizador`.`tamanio` ;

CREATE TABLE IF NOT EXISTS `cotizador`.`tamanio` (
  `id_tamanio` INT(11) NOT NULL AUTO_INCREMENT,
  `tamanio` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tamanio`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cotizador`.`proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cotizador`.`proveedor` ;

CREATE TABLE IF NOT EXISTS `cotizador`.`proveedor` (
  `id_proveedor` INT(11) NOT NULL AUTO_INCREMENT,
  `proveedor` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cotizador`.`material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cotizador`.`material` ;

CREATE TABLE IF NOT EXISTS `cotizador`.`material` (
  `id_material` INT(11) NOT NULL AUTO_INCREMENT,
  `id_categoria` INT(11) NULL DEFAULT NULL,
  `id_clase` INT(11) NULL DEFAULT NULL,
  `medida` VARCHAR(30) NULL DEFAULT NULL,
  `id_tamanio` INT(11) NULL DEFAULT NULL,
  `id_proveedor` INT(11) NULL DEFAULT NULL,
  `precio` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id_material`),
  INDEX `id_categoria` (`id_categoria` ASC),
  INDEX `id_clase` (`id_clase` ASC),
  INDEX `id_tamanio` (`id_tamanio` ASC),
  INDEX `id_proveedor` (`id_proveedor` ASC),
  CONSTRAINT `material_ibfk_1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `cotizador`.`categoria` (`id_categoria`),
  CONSTRAINT `material_ibfk_2`
    FOREIGN KEY (`id_clase`)
    REFERENCES `cotizador`.`clase` (`id_clase`),
  CONSTRAINT `material_ibfk_3`
    FOREIGN KEY (`id_tamanio`)
    REFERENCES `cotizador`.`tamanio` (`id_tamanio`),
  CONSTRAINT `material_ibfk_4`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `cotizador`.`proveedor` (`id_proveedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cotizador`.`medida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cotizador`.`medida` ;

CREATE TABLE IF NOT EXISTS `cotizador`.`medida` (
  `id_medida` INT(11) NOT NULL AUTO_INCREMENT,
  `largo` VARCHAR(20) NULL DEFAULT NULL,
  `ancho` VARCHAR(20) NULL DEFAULT NULL,
  `grosor` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id_medida`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cotizador`.`elemento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cotizador`.`elemento` ;

CREATE TABLE IF NOT EXISTS `cotizador`.`elemento` (
  `id_elemento` INT(11) NOT NULL AUTO_INCREMENT,
  `id_material` INT(11) NULL DEFAULT NULL,
  `id_producto` INT(11) NULL DEFAULT NULL,
  `id_proyecto` INT(11) NULL DEFAULT NULL,
  `cantidad` VARCHAR(200) NULL DEFAULT NULL,
  `importe` VARCHAR(200) NULL DEFAULT NULL,
  `id_medida` INT(11) NULL DEFAULT NULL,
  `pies` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id_elemento`),
  INDEX `id_material` (`id_material` ASC),
  INDEX `id_producto` (`id_producto` ASC),
  INDEX `id_proyecto` (`id_proyecto` ASC),
  INDEX `id_medida` (`id_medida` ASC),
  CONSTRAINT `elemento_ibfk_1`
    FOREIGN KEY (`id_material`)
    REFERENCES `cotizador`.`material` (`id_material`),
  CONSTRAINT `elemento_ibfk_2`
    FOREIGN KEY (`id_producto`)
    REFERENCES `cotizador`.`producto` (`id_producto`),
  CONSTRAINT `elemento_ibfk_3`
    FOREIGN KEY (`id_proyecto`)
    REFERENCES `cotizador`.`proyecto` (`id_proyecto`),
  CONSTRAINT `elemento_ibfk_4`
    FOREIGN KEY (`id_medida`)
    REFERENCES `cotizador`.`medida` (`id_medida`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cotizador`.`extra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cotizador`.`extra` ;

CREATE TABLE IF NOT EXISTS `cotizador`.`extra` (
  `id_extra` INT(11) NOT NULL AUTO_INCREMENT,
  `id_producto` INT(11) NULL DEFAULT NULL,
  `extra` VARCHAR(200) NULL DEFAULT NULL,
  `importe` VARCHAR(200) NULL DEFAULT NULL,
  `id_proyecto` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_extra`),
  INDEX `id_producto` (`id_producto` ASC),
  CONSTRAINT `extra_ibfk_1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `cotizador`.`producto` (`id_producto`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
